chore: update workflow for daily updating on main branch

diff --git a/.github/workflows/update.yaml b/.github/workflows/update.yaml
--- a/.github/workflows/update.yaml
+++ b/.github/workflows/update.yaml
@@ -3,9 +3,9 @@ name: Badge Updater
 on:
   push:
     branches:
-      - Data
+      - Data2
   schedule:
-    - cron: "0 0 * * *"
+    - cron: "38 9 * * *"
 
 permissions:
   contents: write
@@ -22,18 +22,28 @@ jobs:
       - name: Cache and setup rust
         uses: actions-rust-lang/setup-rust-toolchain@v1
 
-      - name: Setup python
-        run: python -m pip install wikitextparser
-
       - name: Test Badges
         run: |
           cd BadgeUpdater
-          cargo run
+          RUST_LOG=debug cargo run
 
       - name: Push to github
+        if: ${{ always() }}
         run: |
-          git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git config user.name "badge-updater[bot]"
+          git config user.email "badge-updater[bot]@users.noreply.github.com"
           git add .
           git commit -m "Automated daily data updating" || echo "No changes to commit"
           git push
+
+      - name: Upload Logs
+        uses: actions/upload-artifact@v6
+        with:
+          name: Logs.txt
+          path: BadgeUpdater/badges.temp.txt
+
+      - name: Fail workflow if previous steps failed
+        if: ${{ failure() }}
+        run: |
+          echo "One or more previous steps failed; failing the workflow."
+          exit 1
